"use strict";
/**
 * A library of chord progressions that actually appear in music, annotated so
 * a learner can hear *why* each one works rather than just copying it.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROGRESSION_CATEGORY_LABELS = exports.PROGRESSIONS_BY_ID = exports.PROGRESSIONS = void 0;
exports.progressionsByCategory = progressionsByCategory;
exports.getProgression = getProgression;
exports.PROGRESSIONS = [
    {
        id: 'i-iv-v-i',
        name: 'The Authentic Cadence Loop',
        romans: ['I', 'IV', 'V', 'I'],
        mode: 'major',
        category: 'foundational',
        why: 'Home → away → maximum tension → home. The V chord contains the leading tone, which pulls up a semitone into the tonic. This is the sentence structure of tonal music.',
        heardIn: ['La Bamba', 'Twist and Shout', 'most folk and blues'],
        difficulty: 1,
    },
    {
        id: 'i-v-vi-iv',
        name: 'The Four Chords',
        romans: ['I', 'V', 'vi', 'IV'],
        mode: 'major',
        category: 'pop',
        why: 'A deceptive cadence at its heart: V resolves to vi instead of I, so the loop never truly lands. That unresolved quality is exactly why it can repeat forever.',
        heardIn: ['Let It Be', "Don't Stop Believin'", 'With or Without You', 'Someone Like You'],
        difficulty: 1,
    },
    {
        id: 'vi-iv-i-v',
        name: 'The Sensitive Female Progression',
        romans: ['vi', 'IV', 'I', 'V'],
        mode: 'major',
        category: 'pop',
        why: 'The same four chords rotated to start on the relative minor. Starting minor and passing through major makes it feel like it is climbing out of something.',
        heardIn: ['Zombie', 'Africa', 'Save Tonight', 'Grenade'],
        difficulty: 1,
    },
    {
        id: 'i-vi-iv-v',
        name: 'The 50s Progression',
        romans: ['I', 'vi', 'IV', 'V'],
        mode: 'major',
        category: 'pop',
        why: 'A textbook descent from tonic through a tonic substitute, into predominant and dominant. Every step is functionally "correct", which is why it sounds so wholesome.',
        heardIn: ['Stand By Me', 'Earth Angel', 'Every Breath You Take'],
        difficulty: 1,
    },
    {
        id: 'ii-v-i',
        name: 'The ii–V–I',
        romans: ['ii7', 'V7', 'Imaj7'],
        mode: 'major',
        category: 'jazz',
        why: 'The single most important cadence in jazz. Roots move down in fifths, and the guide tones (3rds and 7ths) move by semitone — the smoothest possible voice leading.',
        heardIn: ['Autumn Leaves', 'Fly Me to the Moon', 'thousands of standards'],
        difficulty: 2,
    },
    {
        id: 'minor-ii-v-i',
        name: 'Minor ii–V–i',
        romans: ['iiø7', 'V7', 'i7'],
        mode: 'minor',
        category: 'jazz',
        why: 'The minor version. The half-diminished ii and the altered V create far more tension, which makes the arrival on i land harder.',
        heardIn: ['Blue Bossa', 'Alone Together', 'Summertime'],
        difficulty: 3,
    },
    {
        id: 'circle-of-fifths',
        name: 'Circle of Fifths Turnaround',
        romans: ['iii7', 'vi7', 'ii7', 'V7'],
        mode: 'major',
        category: 'jazz',
        why: 'Each root falls a fifth to the next. Root motion by descending fifth is the strongest progression in tonal harmony — this is four of them in a row.',
        heardIn: ['I Will Survive', 'Fly Me to the Moon', 'Autumn Leaves'],
        difficulty: 2,
    },
    {
        id: 'i-vi-ii-v',
        name: 'Rhythm Changes Turnaround',
        romans: ['I', 'vi7', 'ii7', 'V7'],
        mode: 'major',
        category: 'jazz',
        why: 'The last two bars of thousands of standards. It resets the ear to the top of the form without ever leaving the key.',
        heardIn: ['I Got Rhythm', 'Oleo', 'Anthropology'],
        difficulty: 2,
    },
    {
        id: 'twelve-bar',
        name: '12-Bar Blues',
        romans: ['I7', 'I7', 'I7', 'I7', 'IV7', 'IV7', 'I7', 'I7', 'V7', 'IV7', 'I7', 'V7'],
        mode: 'major',
        category: 'blues',
        why: 'Every chord is a dominant 7th, which is theoretically "wrong" — but the blues treats the b7 as a colour, not as tension. The form is a 12-bar question-and-answer.',
        heardIn: ['Sweet Home Chicago', 'Johnny B. Goode', 'Hound Dog'],
        beatsPerChord: 4,
        difficulty: 2,
    },
    {
        id: 'quick-change-blues',
        name: 'Quick-Change Blues',
        romans: ['I7', 'IV7', 'I7', 'I7', 'IV7', 'IV7', 'I7', 'VI7', 'ii7', 'V7', 'I7', 'V7'],
        mode: 'major',
        category: 'blues',
        why: 'The IV arrives in bar 2 instead of bar 5, and the turnaround uses a secondary dominant (VI7) to set up ii. More motion, more sophistication.',
        heardIn: ['Stormy Monday', 'jazz-blues heads'],
        beatsPerChord: 4,
        difficulty: 3,
    },
    {
        id: 'andalusian',
        name: 'Andalusian Cadence',
        romans: ['i', 'VII', 'VI', 'V'],
        mode: 'minor',
        category: 'modal',
        why: 'A stepwise descent from the tonic to a major V. The major chord at the end is borrowed from harmonic minor, which is where the flamenco flavour comes from.',
        heardIn: ['Hit the Road Jack', 'Sultans of Swing', 'Runaway'],
        difficulty: 2,
    },
    {
        id: 'i-bvii-iv',
        name: 'The Mixolydian Rock Loop',
        romans: ['I', 'bVII', 'IV'],
        mode: 'major',
        category: 'modal',
        why: 'The bVII is borrowed from Mixolydian. Without a leading tone there is no pull home, so the loop feels planted rather than resolving.',
        heardIn: ['Sweet Home Alabama', 'Sympathy for the Devil', 'Werewolves of London'],
        difficulty: 2,
    },
    {
        id: 'i-bvi-bvii',
        name: 'The Epic Minor Climb',
        romans: ['i', 'bVI', 'bVII'],
        mode: 'minor',
        category: 'cinematic',
        why: 'Two major chords rising by step out of a minor tonic. Rising root motion plus major quality reads as heroic; staying in minor keeps it serious.',
        heardIn: ['film trailers', 'Skyfall', 'countless video game scores'],
        difficulty: 2,
    },
    {
        id: 'i-iii-vi-iv',
        name: 'The Bittersweet Turn',
        romans: ['I', 'iii', 'vi', 'IV'],
        mode: 'major',
        category: 'pop',
        why: 'The iii chord shares two notes with I but adds the leading tone as a colour rather than a tension. It softens the move into the relative minor.',
        heardIn: ['Creep-adjacent indie', 'Kiss Me', 'Yellow'],
        difficulty: 2,
    },
    {
        id: 'royal-road',
        name: 'The Royal Road (王道進行)',
        romans: ['IVmaj7', 'V7', 'iii7', 'vi7'],
        mode: 'major',
        category: 'pop',
        why: 'The V resolves deceptively to iii instead of I, then slides to vi. It never touches the tonic, so it feels permanently yearning — the backbone of J-pop and anime themes.',
        heardIn: ['J-pop', 'city pop', 'anime openings'],
        difficulty: 3,
    },
    {
        id: 'backdoor',
        name: 'The Backdoor Cadence',
        romans: ['iv7', 'bVII7', 'Imaj7'],
        mode: 'major',
        category: 'jazz',
        why: 'Arriving at the tonic from bVII7 rather than V7. Borrowed from the parallel minor, it resolves with warmth instead of tension.',
        heardIn: ['Steely Dan', 'gospel', 'neo-soul'],
        difficulty: 4,
    },
    {
        id: 'coltrane-changes',
        name: 'Coltrane Changes',
        romans: ['Imaj7', 'bVI7', 'bVImaj7', 'III7', 'IIImaj7'],
        mode: 'major',
        category: 'jazz',
        why: 'Modulation by major thirds, dividing the octave into three equal parts. It abandons the circle of fifths entirely and substitutes symmetry for function.',
        heardIn: ['Giant Steps', 'Countdown'],
        difficulty: 5,
    },
    {
        id: 'neo-soul-loop',
        name: 'Neo-Soul Loop',
        romans: ['imaj7', 'IVmaj7', 'bVII9', 'bIIImaj7'],
        mode: 'minor',
        category: 'gospel',
        why: 'Extended chords with common tones held across every change. The harmony moves but the top voice barely does — that stillness is the neo-soul signature.',
        heardIn: ['D’Angelo', 'Erykah Badu', 'Hiatus Kaiyote'],
        difficulty: 4,
    },
    {
        id: 'house-vamp',
        name: 'Deep House Vamp',
        romans: ['i9', 'IVmaj7', 'i9', 'bVImaj7'],
        mode: 'minor',
        category: 'electronic',
        why: 'Two chords doing almost all the work, with 9ths adding motion inside a static loop. Harmonic simplicity leaves room for rhythm and texture to carry the track.',
        heardIn: ['deep house', 'lo-fi', 'downtempo'],
        difficulty: 2,
    },
    {
        id: 'picardy',
        name: 'Picardy Third',
        romans: ['i', 'iv', 'V', 'I'],
        mode: 'minor',
        category: 'foundational',
        why: 'A minor piece that ends on a major tonic. The final chord raises the third by a semitone — a small change that reads as sudden light.',
        heardIn: ['Bach chorales', 'Renaissance polyphony', 'dramatic film cues'],
        difficulty: 3,
    },
    {
        id: 'secondary-dominant',
        name: 'Secondary Dominant Chain',
        romans: ['I', 'VI7', 'ii7', 'V7', 'I'],
        mode: 'major',
        category: 'jazz',
        why: 'VI7 is "the V of ii" — a chord borrowed from another key purely to make the next chord feel inevitable. This is the gateway to chromatic harmony.',
        heardIn: ['jazz standards', 'Beatles bridges', 'musical theatre'],
        difficulty: 3,
    },
    {
        id: 'tritone-sub',
        name: 'Tritone Substitution',
        romans: ['ii7', 'bII7', 'Imaj7'],
        mode: 'major',
        category: 'jazz',
        why: 'bII7 shares its tritone with V7, so it resolves the same way — but its root falls chromatically into the tonic. Same function, sleeker bass line.',
        heardIn: ['bebop', 'bossa nova', 'Michel Legrand'],
        difficulty: 4,
    },
    {
        id: 'lament-bass',
        name: 'The Lament Bass',
        romans: ['i', 'V/3', 'bVI', 'V'],
        mode: 'minor',
        category: 'cinematic',
        why: 'The bass walks down by semitone while the chords change above it. Descending chromatic bass has meant grief in Western music for four hundred years.',
        heardIn: ['Dido’s Lament', 'Hotel California', 'Stairway to Heaven'],
        difficulty: 3,
    },
    {
        id: 'plagal',
        name: 'Plagal (Amen) Cadence',
        romans: ['IV', 'I'],
        mode: 'major',
        category: 'foundational',
        why: 'IV to I has no leading tone, so it settles rather than resolves. It sounds like a conclusion arriving gently instead of snapping shut.',
        heardIn: ['hymns', 'gospel', 'Let It Be outro'],
        difficulty: 1,
    },
    {
        id: 'modal-interchange',
        name: 'Modal Interchange Ballad',
        romans: ['Imaj7', 'iv7', 'Imaj7', 'bVImaj7'],
        mode: 'major',
        category: 'cinematic',
        why: 'iv and bVI are borrowed from the parallel minor. Dropping a minor-mode chord into a major song is the most reliable way to make a listener feel wistful.',
        heardIn: ['Radiohead', 'Beach Boys', 'Disney ballads'],
        difficulty: 4,
    },
];
exports.PROGRESSIONS_BY_ID = Object.fromEntries(exports.PROGRESSIONS.map((p) => [p.id, p]));
exports.PROGRESSION_CATEGORY_LABELS = {
    foundational: 'Foundations',
    pop: 'Pop & Rock',
    jazz: 'Jazz',
    blues: 'Blues',
    cinematic: 'Cinematic',
    electronic: 'Electronic',
    gospel: 'Gospel & Soul',
    modal: 'Modal',
};
function progressionsByCategory(category) {
    return exports.PROGRESSIONS.filter((p) => p.category === category);
}
function getProgression(id) {
    const p = exports.PROGRESSIONS_BY_ID[id];
    if (!p)
        throw new Error(`Unknown progression: ${id}`);
    return p;
}
